name: Create release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:          

jobs:
  deb-control-file-build:
    name: Generate Debian Package
    runs-on: ubuntu-20.04

    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: |
          sudo apt update && sudo apt install -y libpam0g-dev libcurl4-openssl-dev libldap2-dev
          make
      
      - name: Update control file with current version
        run: |
          export VERSION=`echo ${{ steps.tagName.outputs.tag }} | sed 's/^v//'`      
          sed -i "s/0.0.0/${VERSION}/" packaging/deb/control.json
          cat packaging/deb/control.json    
          ls -latr

      - name: Generate Control File
        id: control-gen
        uses: Nightwind-Developments/debian-control-file-builder@latest
        with:
          config-file: 'packaging/deb/control.json'
          deps-file: 'packaging/deb/dependencies.txt'
          output-path: 'packaging/output'

      - name: Prints Output File Path
        run: echo "${{ steps.control-gen.outputs.control_file_path }}"

      - name: Confirms Control File is Present
        run: ls ${{ steps.control-gen.outputs.control_file_path }}

      - name: Prepare files
        run: |
          ls -la packaging/output      
          sudo cp ${{ github.workspace }}/pam_oauth2_device.so packaging/output/
          sudo cp ${{ github.workspace }}/config_template.json packaging/output/config.json

      - name: Prints Contents of Input Resources
        run: ls -l "packaging/output/"

      - name: Build Docker Container & Run Debian Packer
        uses: Nightwind-Developments/debian-packer@latest
        id: container
        with:
          input_dir: 'packaging/output/'
          output_dir: 'packaging/output/'
          layout_map_file: 'packaging/deb/layout_map.json'
          package_name: 'pam-oauth2-device'
          package_version: '${{ steps.tagName.outputs.tag }}'
          package_arch: 'all'

      - name: Prints Contents of Input Resources
        run: ls -l "packaging/output/"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          draft: true
          files: |
            *.deb


